# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
    ]
