# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20171021_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='chap',
        ),
    ]
