
ok = {   "Genesis": 50, 
    "Exodus": 40, 
    "Leviticus": 27, 
    "Numbers": 36, 
    "Deuteronomy": 34,
    "Joshua": 24,
    "Judges": 21,
    "Ruth": 4,
    "1_Samuel": 31,
    "2_Samuel": 24,
    "1_Kings": 22,
    "2_Kings": 25,
    "1_Chronicles": 29,
    "2_Chronicles": 36,
    "Ezra": 10,
    "Nehemiah": 13,
    "Esther": 10,
    "Job": 42,
    "Psalms": 150,
    "Proverbs": 31,
    "Ecclesiastes": 12,
    "Song_Of_Songs": 8,
    "Isaiah": 66,
    "Jeremiah": 52,
    "Lamentations": 5,
    "Ezekiel": 48,
    "Daniel": 12,
    "Hosea": 14,
    "Joel": 3,
    "Amos": 9,
    "Obadiah": 1,
    "Jonah": 4,
    "Micah": 7,
    "Nahum": 3,
    "Habakkuk": 3,
    "Zephaniah": 3,
    "Haggai": 2,
    "Zechariah": 14,
    "Malachi": 4,
    "Matthew" :28,
    "Mark": 16,
    "Luke": 24,
    "John": 21,
    "Acts": 28,
    "Romans": 16,
    "1_Corinthians":16,
    "2_Corinthians":13,
    "Galations":6,
    "Ephesians": 6,
    "Philippians": 4,
    "Colossians": 4,
    "1_Thessalonians": 5,
    "2_Thessalonians": 3,
    "1_Timothy": 6,
    "2_Timothy": 4,
    "Titus": 3,
    "Philemon": 1,
    "Hebrews": 13,
    "James": 5,
    "1_Peter": 5,
    "2_Peter": 3,
    "1_John": 5,
    "2_John": 1,
    "3_John": 1,
    "Jude": 1,
    "Revelations": 22
}

def bibdic():
    return ok